env:
  browser: true
  commonjs: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  indent:    
    - error    
    - 4    
    - SwitchCase: 1
  quotes:    
    - error    
    - single  
  # semi:    
  #   - error    
  #   - never  
  # linebreak-style:    
  #   - error    
  #   - unix  
  no-console: 0
# globals:    
#   __filename: true    
#   __dirname: truenp