export const ACTIONS = {
    ADD_NEW_CHAT: 'ADD_NEW_CHAT',
    ADD_NEW_MESSAGE: 'ADD_NEW_MESSAGE',
    CHATS_REQUEST: 'CHAT_REQUEST',
    CHATS_SUCCESS: 'CHATS_SUCCESS',
    CHATS_FAIL: 'CHATS_SUCCESS', 
}